kind: Deployment
apiVersion: apps/v1
metadata:
   name: mrdevops
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: mrdevops
   template:
      metadata:
        labels:
          app: mrdevops
      spec:
       containers:
        - name: mrdevops
          image: kininam/kubernetes
          imagePullPolicy: Always
          ports:
          - containerPort: 80
---
kind: Service                             
apiVersion: v1
metadata:
  name: mrdevops
  labels:
    app: mrdevops
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: mrdevops                    
  type: LoadBalancer   
